version: "3.0"

services:
  qr-code-service:
    build: qr-code-service
    image: pjanczyk/qr-code-generator_web

  web:
    build: web
    image: pjanczyk/qr-code-generator_qr-code-service
    ports:
      - "80:80"
