version: "3.0"

services:
  qr-code-service:
    build: ./qr-code-service
    image: pjanczyk/qr-code-generator_qr-code-service

  web:
    build: ./web
    image: pjanczyk/qr-code-generator_web
    ports:
      - "3007:80"
    environment:
      QR_CODE_GENERATOR_BASE_URL: http://localhost:3007
      QR_CODE_GENERATOR_QR_CODE_SERVICE_ADDRESS: qr-code-service:5000
